DROP TABLE IF EXISTS products.products;
DROP TABLE IF EXISTS products.categories;

CREATE TABLE products.categories
(
    category_id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    category_title VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

ALTER TABLE products.categories
    ADD CONSTRAINT uc_categories_category_title UNIQUE (category_title);

CREATE TABLE products.products
(
    product_id    UUID         NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    product_title VARCHAR(255) NOT NULL,
    image_url     VARCHAR(255) NOT NULL,
    price_unit    DECIMAL      NOT NULL,
    quantity      INTEGER      NOT NULL,
    category_id   INTEGER      NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

ALTER TABLE products.products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES products.categories (category_id);